[package]
name = "bitdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rkyv = "0.7.38"
bincode = "1.3.3"
serde = { version ="1.0.137", features=["derive"] }
dashmap = "5.3.3"
